version: "3"

services:
  fastapi:
    build: fastapi/
    ports:
      - 8000:8000
    networks:
      - deploy_network
    volumes:
      - ./fastapi:/fastapi/fastapi
    container_name: fastapi
    command: sh -c "cd fastapi && pip install -r requirements.txt && rm -rf finish_processed_files uploaded_files && mkdir finish_processed_files uploaded_files  && uvicorn server:app --host 0.0.0.0 --port 8000"

networks:
  deploy_network:
    driver: bridge
